using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using Object=UnityEngine.Object;
namespace UpIzUpMini.EditorTools {public static class Mini174CoastAndSpacing {
 const string Scene="Assets/UpIzUpMini/Scenes/GrandBayProof_ExpansionImport.unity",Out="Logs/Tasks/MINI-174",Art="Assets/UpIzUpMini/Art/Environment/Mini174";
 class Lot{public Transform t;public Bounds local;public Vector3 original,scale;public Quaternion rotation;public Vector2[] Polygon(){var b=local;return new[]{P(b.min.x,b.min.z),P(b.max.x,b.min.z),P(b.max.x,b.max.z),P(b.min.x,b.max.z)};}Vector2 P(float x,float z){var p=t.TransformPoint(new Vector3(x,0,z));return new Vector2(p.x,p.z);}}
 static bool Clash(Lot a,Lot b,float gap=.18f){var pa=a.Polygon();var pb=b.Polygon();foreach(var poly in new[]{pa,pb})for(int i=0;i<2;i++){Vector2 d=poly[i+1]-poly[i];var axis=new Vector2(-d.y,d.x).normalized;float amin=pa.Min(p=>Vector2.Dot(p,axis)),amax=pa.Max(p=>Vector2.Dot(p,axis)),bmin=pb.Min(p=>Vector2.Dot(p,axis)),bmax=pb.Max(p=>Vector2.Dot(p,axis));if(amax+gap<=bmin||bmax+gap<=amin)return false;}return true;}
 static Lot[] Lots(){return Object.FindObjectsByType<Transform>(FindObjectsSortMode.None).Where(t=>t.name.StartsWith("Lalay_House_")||t.name.StartsWith("Highland_House_")||t.name.StartsWith("Lalay_Home_")||t.name.StartsWith("ExpansionHouse_")).Select(t=>{bool first=true;Bounds b=new Bounds();foreach(var f in t.GetComponentsInChildren<MeshFilter>()){if(!f.GetComponent<Renderer>() || !f.gameObject.activeInHierarchy)continue;var q=f.sharedMesh.bounds;foreach(float x in new[]{q.min.x,q.max.x})foreach(float y in new[]{q.min.y,q.max.y})foreach(float z in new[]{q.min.z,q.max.z}){var p=t.InverseTransformPoint(f.transform.TransformPoint(new Vector3(x,y,z)));if(first){b=new Bounds(p,Vector3.zero);first=false;}else b.Encapsulate(p);}}return new Lot{t=t,local=b,original=t.position,scale=t.localScale,rotation=t.rotation};}).Where(l=>l.local.size.sqrMagnitude>.001f).OrderBy(l=>l.t.name.StartsWith("Lalay_Home_")?1:0).ThenBy(l=>l.t.name).ToArray();}
 static float Ground(Vector3 p,MeshCollider[] terrain){float y=float.NegativeInfinity;foreach(var c in terrain)if(c.Raycast(new Ray(new Vector3(p.x,200,p.z),Vector3.down),out var hit,500))y=Mathf.Max(y,hit.point.y);return y;}
 static bool RoadClear(Lot l,MeshCollider[] roads){var poly=l.Polygon();for(int i=0;i<5;i++)for(int j=0;j<5;j++){var p=Vector2.Lerp(Vector2.Lerp(poly[0],poly[1],i/4f),Vector2.Lerp(poly[3],poly[2],i/4f),j/4f);foreach(var r in roads)if(r.Raycast(new Ray(new Vector3(p.x,200,p.y),Vector3.down),out _,500))return false;}return true;}
 public static void Apply(){try{Directory.CreateDirectory(Out);Directory.CreateDirectory(Art);AssetDatabase.Refresh();var scene=EditorSceneManager.OpenScene(Scene);var lots=Lots();var terrain=Object.FindObjectsByType<MeshCollider>(FindObjectsSortMode.None).Where(c=>c.name.Contains("Terrain")).ToArray();var roads=Object.FindObjectsByType<MeshCollider>(FindObjectsSortMode.None).Where(c=>c.name.Contains("Road")).ToArray();var report=new List<string>();int before=0;for(int i=0;i<lots.Length;i++)for(int j=i+1;j<lots.Length;j++)if(Clash(lots[i],lots[j])){before++;report.Add("BEFORE "+lots[i].t.name+" / "+lots[j].t.name);}
 var fixedLots=new List<Lot>();int changed=0;foreach(var lot in lots){if(!fixedLots.Any(other=>Clash(lot,other))&&RoadClear(lot,roads)){fixedLots.Add(lot);continue;}bool found=false;float oldGround=Ground(lot.original,terrain);foreach(float distance in new[]{0f,.5f,1f,2f,3f,4f,6f,8f,10f,12f,16f,20f}){foreach(float lateral in new[]{0f,-.5f,.5f,-1f,1f,-2f,2f,-3f,3f,-5f,5f}){foreach(float scale in new[]{1f,.94f,.88f,.82f}){lot.t.localScale=new Vector3(lot.scale.x*scale,lot.scale.y,lot.scale.z*scale);var pos=lot.original-lot.t.forward*distance+lot.t.right*lateral;float ground=Ground(pos,terrain);if(float.IsNegativeInfinity(ground))continue;pos.y=lot.original.y+ground-oldGround;lot.t.position=pos;if(fixedLots.Any(other=>Clash(lot,other))||!RoadClear(lot,roads))continue;found=true;break;}if(found)break;}if(found)break;}if(!found){lot.t.position=lot.original;lot.t.localScale=lot.scale;throw new Exception("No clear lot for "+lot.t.name);}changed++;report.Add("FIX "+lot.t.name+" from="+lot.original+" to="+lot.t.position+" scale="+lot.t.localScale);fixedLots.Add(lot);}
 int after=0;for(int i=0;i<lots.Length;i++)for(int j=i+1;j<lots.Length;j++)if(Clash(lots[i],lots[j]))after++;if(after!=0)throw new Exception("Remaining house clashes "+after);
 BuildWall(terrain);report.Add("PASS houses="+lots.Length+" clashesBefore="+before+" clashesAfter="+after+" adjusted="+changed);EditorSceneManager.MarkSceneDirty(scene);EditorSceneManager.SaveScene(scene);AssetDatabase.SaveAssets();File.WriteAllLines(Out+"/Spacing.txt",report);Debug.Log("MINI174_PASS "+report.Last());Render();}catch(Exception e){Debug.LogException(e);EditorApplication.Exit(1);}}
 static float Coast(float z){return z < -160?250:z < -60?250+(z+160)*.55f:305+(z+60)*.25f;}
 static void BuildWall(MeshCollider[] terrain){var old=GameObject.Find("MINI174_BaySeawall");if(old)Object.DestroyImmediate(old);var root=new GameObject("MINI174_BaySeawall").transform;var concrete=Mat("WeatheredConcrete",new Color(.52f,.51f,.45f));var cap=Mat("ConcreteCap",new Color(.68f,.66f,.58f));var roads=Object.FindObjectsByType<MeshCollider>(FindObjectsSortMode.None).Where(c=>c.name.Contains("Road")).ToArray();int count=0;
 // Follow the saved shoreline through and beyond the roundabout. The wall
 // remains landward of the water; solid collision, no change to the road mesh.
 for(float z=-159;z<36;z+=3){var a=new Vector3(Coast(z)-1.1f,0,z);var b=new Vector3(Coast(z+3)-1.1f,0,z+3);float ga=Ground(a,terrain),gb=Ground(b,terrain);if(float.IsNegativeInfinity(ga)||float.IsNegativeInfinity(gb))continue;float ground=Mathf.Max(ga,gb);var mid=(a+b)*.5f;bool onRoad=roads.Any(r=>r.Raycast(new Ray(new Vector3(mid.x,200,mid.z),Vector3.down),out _,500));if(onRoad)throw new Exception("Seawall intersects road near "+mid);float height=1.15f;var q=Quaternion.LookRotation((b-a).normalized);Box(root,"Seawall",new Vector3(mid.x,ground+height*.5f-.20f,mid.z),new Vector3(.55f,height,Vector3.Distance(a,b)+.09f),q,concrete);Box(root,"Cap",new Vector3(mid.x,ground+height-.18f,mid.z),new Vector3(.68f,.13f,Vector3.Distance(a,b)+.10f),q,cap);count++;}
 File.WriteAllText(Out+"/Seawall.txt","segments="+count+"\nheight=1.15m; capWidth=.68m; shoreInset=1.1m; z=-159..36\nExact real-world dimensions unverified; user-directed coastal representation.");}
 static Material Mat(string n,Color col){var path=Art+"/"+n+".mat";var m=AssetDatabase.LoadAssetAtPath<Material>(path);if(!m){m=new Material(Shader.Find("Standard"));AssetDatabase.CreateAsset(m,path);}m.color=col;m.enableInstancing=true;return m;}
 static void Box(Transform root,string n,Vector3 p,Vector3 size,Quaternion q,Material mat){var g=GameObject.CreatePrimitive(PrimitiveType.Cube);g.name=n;g.transform.SetParent(root);g.transform.SetPositionAndRotation(p,q);g.transform.localScale=size;g.GetComponent<Renderer>().sharedMaterial=mat;g.isStatic=true;}
 public static void Validate(){try{EditorSceneManager.OpenScene(Scene);var lots=Lots();var roads=Object.FindObjectsByType<MeshCollider>(FindObjectsSortMode.None).Where(c=>c.name.Contains("Road")).ToArray();int pairs=0,roadHits=0;for(int i=0;i<lots.Length;i++){if(!RoadClear(lots[i],roads))roadHits++;for(int j=i+1;j<lots.Length;j++)if(Clash(lots[i],lots[j]))pairs++;}var wall=GameObject.Find("MINI174_BaySeawall");int colliders=wall?wall.GetComponentsInChildren<BoxCollider>().Length:0;if(pairs!=0||roadHits!=0||colliders!=130)throw new Exception("Validation: housePairs="+pairs+" roadHits="+roadHits+" wallColliders="+colliders);File.WriteAllText(Out+"/Validation.txt","PASS saved-scene reload\nhouses="+lots.Length+"\nhouseOverlapPairs="+pairs+"\nhouseRoadHits="+roadHits+"\nwallSegments=65\nwallColliders="+colliders+"\nMinimum tested house separation .18m, including conservative hidden source-mesh envelopes.\n");Debug.Log("MINI174_VALIDATION_PASS");EditorApplication.Exit(0);}catch(Exception e){Debug.LogException(e);EditorApplication.Exit(1);}} public static void Render(){Directory.CreateDirectory(Out+"/Renders");foreach(var c in Object.FindObjectsByType<Camera>(FindObjectsSortMode.None))c.enabled=false;RenderSettings.fog=false;var cam=new GameObject("Mini174Evidence").AddComponent<Camera>();cam.farClipPlane=1500;Shot(cam,"BaySeawall",new Vector3(358,50,-126),new Vector3(280,2,-68),60);Shot(cam,"LalaySpacing",new Vector3(28,34,-130),new Vector3(10,9,-157),55);EditorApplication.Exit(0);}
 static void Shot(Camera c,string n,Vector3 p,Vector3 target,float fov){c.transform.position=p;c.transform.LookAt(target);c.fieldOfView=fov;var rt=new RenderTexture(1400,1000,24);c.targetTexture=rt;c.Render();RenderTexture.active=rt;var tex=new Texture2D(1400,1000,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,1400,1000),0,0);tex.Apply();File.WriteAllBytes(Out+"/Renders/"+n+".png",tex.EncodeToPNG());c.targetTexture=null;RenderTexture.active=null;Object.DestroyImmediate(tex);Object.DestroyImmediate(rt);}
}}

